give credit

diff --git a/src/patches.patch b/src/patches.patch
--- a/src/patches.patch
+++ b/src/patches.patch
@@ -1,16 +1,54 @@
+diff -Naur slackware-live-0.4.orig/doc/AUTHORS slackware-live-0.4/doc/AUTHORS
+--- slackware-live-0.4.orig/doc/AUTHORS	2016-07-23 14:20:35.000000000 +0300
++++ slackware-live-0.4/doc/AUTHORS	2017-07-31 00:45:53.381159389 +0300
+@@ -1,5 +1,6 @@
+ Developpers:
+ - Dimitris Tzemos <dijemos@gmail.com> (corrections for slackel,salix)
++- Eric Hameleers <alien@slackware.com> (encryption support)
+ - Frank Endres <frankendres@tuxfamily.org>
+ - Sebastian Reisse <sebastian.j.reisse@gmx.net>
+ 
+diff -Naur slackware-live-0.4.orig/doc/COPYING slackware-live-0.4/doc/COPYING
+--- slackware-live-0.4.orig/doc/COPYING	2016-07-23 14:20:35.000000000 +0300
++++ slackware-live-0.4/doc/COPYING	2017-07-31 00:46:17.691159924 +0300
+@@ -1,4 +1,5 @@
+ Slackware-Live, Copyright Frank Endres, 2010-2014
++# Eric Hameleers <alien@slackware.com> (encryption support)
+ 
+ This software is governed by the CeCILL license under french 
+ law, compatible with the GNU General Public License.
+diff -Naur slackware-live-0.4.orig/doc/ChangeLog slackware-live-0.4/doc/ChangeLog
+--- slackware-live-0.4.orig/doc/ChangeLog	2016-07-23 14:20:35.000000000 +0300
++++ slackware-live-0.4/doc/ChangeLog	2017-07-31 00:46:06.859159686 +0300
+@@ -1,4 +1,5 @@
+ 2015-10-11: Slackware-Live-0.4.5:
++	+ Eric Hameleers <alien@slackware.com> (encryption support)
+ 	+ added support to format partitions using different filesystems (btrfs,ext2,ext3,ext4,reiserfs,jfs,xfs) by [Dimitris Tzemos <dijemos@gmail.com>]
+ 2015-01-15: Slackware-Live-0.4.3: fixed EFI installation
+ 	+ fixed fstab (added /dev/shm tmpfs, needed for Chromium Web browser for example)
+diff -Naur slackware-live-0.4.orig/doc/README slackware-live-0.4/doc/README
+--- slackware-live-0.4.orig/doc/README	2016-07-23 14:20:35.000000000 +0300
++++ slackware-live-0.4/doc/README	2017-07-31 00:46:41.707160452 +0300
+@@ -1,4 +1,5 @@
+ Slackware Live is a live DVD/USB/NFS build and install tool written for Slackware (& Slackware64) Linux:
++- Eric Hameleers <alien@slackware.com> (encryption support)
+ - support GPT and legacy MBR partitionned disks, UEFI and CSM (legacy / BIOS) booting
+ - contains all the necessary to convert an installed system to a live system and vice-versa;
+ - it doesn't need any kernel recompile, but it support seamlessly AUFS and SquashFS-XZ/LZMA if your kernel support them;
 diff -Naur slackware-live-0.4.orig/scripts/build-slackware-live.sh slackware-live-0.4/scripts/build-slackware-live.sh
 --- slackware-live-0.4.orig/scripts/build-slackware-live.sh	2014-02-11 22:32:24.000000000 +0200
-+++ slackware-live-0.4/scripts/build-slackware-live.sh	2017-06-13 04:28:20.172998532 +0300
-@@ -1,4 +1,8 @@
++++ slackware-live-0.4/scripts/build-slackware-live.sh	2017-07-31 00:45:35.591158998 +0300
+@@ -1,4 +1,9 @@
  #!/bin/sh
 +#Dimitris Tzemos <dijemos@gmail.com> (changes for slackel,salix)
++# Eric Hameleers <alien@slackware.com> (encryption support)
 +
 +LIVELABEL="LIVE" #edit in init script too
 +SALIX_FLAVOR="Salix-xfce-14.2"
  
  CMDERROR=1
  PARTITIONERROR=2
-@@ -6,6 +10,11 @@
+@@ -6,6 +11,11 @@
  BOOTERROR=4
  INSUFFICIENTSPACE=5
  
@@ -22,7 +60,7 @@ diff -Naur slackware-live-0.4.orig/scripts/build-slackware-live.sh slackware-liv
  function add_packages() {
  	packagesdirectory=$1
  	rootdirectory=$2
-@@ -50,19 +59,19 @@
+@@ -50,19 +60,19 @@
  	fi
  
  	mount --bind /proc $rootdirectory/proc
@@ -46,7 +84,7 @@ diff -Naur slackware-live-0.4.orig/scripts/build-slackware-live.sh slackware-liv
  		cp `which $prg` $rootdirectory/tmp/initrd-tree/bin/ #UnionFS
  		ldd `which $prg` | sed 's/[^\/]*\(\/[^ ]*\) .*/\1/' | sed 's/[^\/]*\(\/[^ ]*\) .*/\1/' | sed -n /^\\//p | sort -u | while read lib; do
  			if [ -d $rootdirectory/tmp/initrd-tree/lib64 ]
-@@ -72,6 +81,7 @@
+@@ -72,6 +82,7 @@
  		done
  	done
  	
@@ -54,7 +92,7 @@ diff -Naur slackware-live-0.4.orig/scripts/build-slackware-live.sh slackware-liv
  	find $rootdirectory/tmp/initrd-tree/lib/modules/ -name "*.ko" | xargs strip --strip-unneeded
  	cwd=`pwd`
  	cd $rootdirectory/tmp/initrd-tree
-@@ -86,18 +96,23 @@
+@@ -86,18 +97,23 @@
  	#BIOS/syslinux
  	mkdir -p $livedirectory/boot/syslinux
  	cp /usr/share/syslinux/menu.c32 $livedirectory/boot/syslinux/
@@ -85,7 +123,7 @@ diff -Naur slackware-live-0.4.orig/scripts/build-slackware-live.sh slackware-liv
  	#UEFI/elilo
  	if [ `uname -m` == "x86_64" ]; then
  		mkdir -p $livedirectory/EFI/BOOT
-@@ -105,17 +120,23 @@
+@@ -105,17 +121,23 @@
  		cp $livedirectory/boot/initrd.gz $livedirectory/EFI/BOOT/
  		cp $livedirectory/boot/vmlinuz $livedirectory/EFI/BOOT/
  		if [ ! -f $livedirectory/EFI/BOOT/elilo.conf ]; then
@@ -119,7 +157,7 @@ diff -Naur slackware-live-0.4.orig/scripts/build-slackware-live.sh slackware-liv
  		dd if=/dev/zero of=/tmp/efi.img bs=1k count=16384
  		mkdosfs -n "EFIBOOT" /tmp/efi.img
  		mount -o loop /tmp/efi.img /mnt/floppy
-@@ -253,16 +274,16 @@
+@@ -253,16 +275,16 @@
  	if [ `uname -m` == "x86_64" ]; then
  		altboot="-eltorito-alt-boot -no-emul-boot -eltorito-platform efi -eltorito-boot efi.img"
  	fi
@@ -138,7 +176,7 @@ diff -Naur slackware-live-0.4.orig/scripts/build-slackware-live.sh slackware-liv
  	
  	device=`echo $installmedia | cut -c6-8`
  	sectorscount=`cat /sys/block/$device/size`
-@@ -273,15 +294,37 @@
+@@ -273,15 +295,37 @@
  
  	if [ "$installdevice" == "$installmedia" ]; then #install on whole disk: partition and format media
  		if [ `uname -m` == "x86_64" ]; then #EFI/GPT
@@ -164,9 +202,9 @@ diff -Naur slackware-live-0.4.orig/scripts/build-slackware-live.sh slackware-liv
 +			else
 +				efipartition="$installdevice""1"
 +				installmedia="$installdevice""2"
-+				#hybrid MBR with BIOS boot partition (1007K) EFI partition (300M) and live partition
-+				echo -e "2\nn\n\n\n+300M\nef00\nn\n\n\n\n\nr\nh\n1 2\nn\n\ny\n\nn\n\nn\nwq\ny\n" | gdisk $installdevice || return $PARTITIONERROR
-+				#echo -e "2\nn\n\n\n+300M\nef00\nn\n\n\n\n\nn\n128\n\n\nef02\nr\nh\n1 2\nn\n\ny\n\nn\nn\nwq\ny\n" | gdisk $installdevice || return $PARTITIONERROR
++				#hybrid MBR with BIOS boot partition (1007K) EFI partition (32M) and live partition
++				echo -e "2\nn\n\n\n+32M\nef00\nn\n\n\n\n\nr\nh\n1 2\nn\n\ny\n\nn\n\nn\nwq\ny\n" | gdisk $installdevice || return $PARTITIONERROR
++				#echo -e "2\nn\n\n\n+32M\nef00\nn\n\n\n\n\nn\n128\n\n\nef02\nr\nh\n1 2\nn\n\ny\n\nn\nn\nwq\ny\n" | gdisk $installdevice || return $PARTITIONERROR
 +				# set the linux partition bootable
 +				sgdisk -p -A 2:set:2 $installdevice
 +				# confirm it was indeed set correctly
@@ -184,7 +222,7 @@ diff -Naur slackware-live-0.4.orig/scripts/build-slackware-live.sh slackware-liv
  			installmedia="$installdevice$partitionnumber"
  			if (( $mediasize < 2048 ))
  			then heads=128; sectors=32
-@@ -289,11 +332,20 @@
+@@ -289,11 +333,20 @@
  			fi
  			mkdiskimage $installdevice 1 $heads $sectors || return $PARTITIONERROR
  			dd if=/dev/zero of=$installdevice bs=1 seek=446 count=64 >/dev/null 2>&1
@@ -209,7 +247,7 @@ diff -Naur slackware-live-0.4.orig/scripts/build-slackware-live.sh slackware-liv
  	
  	else #install on partition: filesystem check and format if needed
  		partitionnumber=`echo $installmedia | cut -c9-`
-@@ -303,14 +355,14 @@
+@@ -303,14 +356,14 @@
  			umount /mnt/tmp
  			fsck -fy $installmedia >/dev/null 2>&1
  		else #format partition
@@ -226,7 +264,7 @@ diff -Naur slackware-live-0.4.orig/scripts/build-slackware-live.sh slackware-liv
  				;;
  			*)
  				partition=`echo $installmedia | cut -c6-`
-@@ -319,48 +371,72 @@
+@@ -319,48 +372,72 @@
  				if (( $size > 1024 )); then
  					fat32option="-F 32"
  				fi
@@ -320,7 +358,7 @@ diff -Naur slackware-live-0.4.orig/scripts/build-slackware-live.sh slackware-liv
  	else
  		umount /mnt/install
  	fi
-@@ -369,26 +445,120 @@
+@@ -369,26 +446,120 @@
  	return 0
  }
  
@@ -449,7 +487,7 @@ diff -Naur slackware-live-0.4.orig/scripts/build-slackware-live.sh slackware-liv
  
  	sed -i /^root:/d /mnt/install/etc/shadow #setup root password
  	cat /etc/shadow | sed -n /^root:/p >> /mnt/install/etc/shadow
-@@ -397,8 +567,8 @@
+@@ -397,8 +568,8 @@
  		cp -f /etc/rc.d/rc.keymap /mnt/install/etc/rc.d/
  	fi
  	cp -f /etc/profile.d/lang.sh /mnt/install/etc/profile.d/
@@ -460,7 +498,7 @@ diff -Naur slackware-live-0.4.orig/scripts/build-slackware-live.sh slackware-liv
  	fi
  	if [ -f /etc/X11/xorg.conf ]; then
  		cp -f /etc/X11/xorg.conf /mnt/install/etc/X11/
-@@ -411,23 +581,76 @@
+@@ -411,23 +582,76 @@
  		cp -f /etc/hardwareclock /mnt/install/etc/
  	fi
  	#Copy end
@@ -543,7 +581,7 @@ diff -Naur slackware-live-0.4.orig/scripts/build-slackware-live.sh slackware-liv
  		kv=`basename /mnt/install/lib/modules/*`
  		if lsmod | grep -q $SYSINSTALLFS; then
  			moduleslist="$SYSINSTALLFS"
-@@ -445,16 +668,17 @@
+@@ -445,16 +669,17 @@
  		done
  		moduleslist=`echo $moduleslist | sed 's/:$//'`
  		if [ ! -z "$moduleslist" ] && [ "$moduleslist" != "sg" ]; then
@@ -564,7 +602,7 @@ diff -Naur slackware-live-0.4.orig/scripts/build-slackware-live.sh slackware-liv
  		if [ -d /sys/firmware/efi ]; then #UEFI
  			modprobe efivars
  			efipartnum=`gdisk -l $installdevice | grep "EF00" | sed 's/  \+/ /g' | cut -f2 -d' '`
-@@ -462,7 +686,7 @@
+@@ -462,7 +687,7 @@
  			if [ ! -z "$efipartition" ]; then
  				mkdir -p /mnt/efi
  				mount $efipartition /mnt/efi
@@ -573,7 +611,7 @@ diff -Naur slackware-live-0.4.orig/scripts/build-slackware-live.sh slackware-liv
  				if [ -d /mnt/efi/EFI/$efilabel ]; then
  					conflictpart=`cat /mnt/efi/EFI/$efilabel/elilo.conf | grep "append" | sed 's/.*root=\([^ ]*\).*/\1/'`
  					if [ "$conflictpart" == "$systempart" ]
-@@ -476,10 +700,10 @@
+@@ -476,10 +701,10 @@
  				cp /mnt/install/boot/vmlinuz /mnt/efi/EFI/$efilabel/
  				cat > /mnt/efi/EFI/$efilabel/elilo.conf << EOF
  timeout=1
@@ -586,7 +624,7 @@ diff -Naur slackware-live-0.4.orig/scripts/build-slackware-live.sh slackware-liv
      append="root=$systempart ro"
  	read-only
  EOF
-@@ -489,14 +713,14 @@
+@@ -489,14 +714,14 @@
  				fi
  				umount /mnt/efi
  				rmdir /mnt/efi
@@ -604,7 +642,7 @@ diff -Naur slackware-live-0.4.orig/scripts/build-slackware-live.sh slackware-liv
  bmp-colors = 255,0,255,0,255,0
  bmp-table = 60,6,1,16
  bmp-timer = 65,27,0,255
-@@ -514,7 +738,7 @@
+@@ -514,7 +739,7 @@
  
  image = /boot/vmlinuz
  root = $systempart
@@ -613,7 +651,7 @@ diff -Naur slackware-live-0.4.orig/scripts/build-slackware-live.sh slackware-liv
  read-only
  EOF
  			if [ -f /mnt/install/boot/initrd.gz ]; then
-@@ -529,16 +753,228 @@
+@@ -529,16 +754,228 @@
  table = $installdevice
  EOF
  			fi
@@ -846,7 +884,7 @@ diff -Naur slackware-live-0.4.orig/scripts/build-slackware-live.sh slackware-liv
  	return 0
  }
  
-@@ -659,7 +1095,11 @@
+@@ -659,7 +1096,11 @@
  	moduleslist=$4
  	if [ -d "$rootdirectory" ] && [ ! -z "$livedirectory" ]; then
  		if [ -z "$moduleslist" ]; then
@@ -859,7 +897,7 @@ diff -Naur slackware-live-0.4.orig/scripts/build-slackware-live.sh slackware-liv
  		fi
  		init_live $rootdirectory $livedirectory $moduleslist
  	else
-@@ -707,6 +1147,7 @@
+@@ -707,6 +1148,7 @@
  "--usb")
  	livedirectory=$2
  	installmedia=$3
@@ -867,7 +905,7 @@ diff -Naur slackware-live-0.4.orig/scripts/build-slackware-live.sh slackware-liv
  	if [ -d "$livedirectory" ] && [ -b "$installmedia" ]; then
  		livesystemsize=`du -s -m $livedirectory | sed 's/\t.*//'`
  		device=`echo $installmedia | cut -c6-8`
-@@ -718,7 +1159,7 @@
+@@ -718,7 +1160,7 @@
  			echo "error: insufficant space on device '$installmedia'"
  			exit $INSUFFICIENTSPACE
  		else
@@ -876,7 +914,7 @@ diff -Naur slackware-live-0.4.orig/scripts/build-slackware-live.sh slackware-liv
  			exit $!
  		fi
  	else
-@@ -730,6 +1171,14 @@
+@@ -730,6 +1172,14 @@
  	rootdirectory=$2
  	systempart=$3
  	loadersetup=$4
@@ -891,7 +929,7 @@ diff -Naur slackware-live-0.4.orig/scripts/build-slackware-live.sh slackware-liv
  	if [ -d "$rootdirectory" ] && [ -b "$systempart" ]; then
  		systemsize=`du -s -m $rootdirectory | sed 's/\t.*//'`
  		device=`echo $systempart | cut -c6-8`
-@@ -741,11 +1190,14 @@
+@@ -741,11 +1191,14 @@
  			echo "error: insufficant space on device '$systempart'"
  			exit $INSUFFICIENTSPACE
  		else
@@ -908,7 +946,7 @@ diff -Naur slackware-live-0.4.orig/scripts/build-slackware-live.sh slackware-liv
  		exit $CMDERROR
  	fi
  	;;
-@@ -780,7 +1232,7 @@
+@@ -780,7 +1233,7 @@
  	echo "`basename $0` --module root_dir live_dir module_file [-xz|-gzip] [-optional]"
  	echo "`basename $0` --iso live_dir iso_file"
  	echo "`basename $0` --usb live_dir device"
@@ -919,20 +957,21 @@ diff -Naur slackware-live-0.4.orig/scripts/build-slackware-live.sh slackware-liv
  	exit $CMDERROR
 diff -Naur slackware-live-0.4.orig/scripts/init slackware-live-0.4/scripts/init
 --- slackware-live-0.4.orig/scripts/init	2014-02-07 11:04:23.000000000 +0200
-+++ slackware-live-0.4/scripts/init	2017-06-13 04:30:03.303993006 +0300
-@@ -1,12 +1,29 @@
++++ slackware-live-0.4/scripts/init	2017-07-31 00:45:03.005158281 +0300
+@@ -1,4 +1,12 @@
  #!/bin/ash
- 
++# Eric Hameleers <alien@slackware.com> (encryption support)
++
 +LIVELABEL="LIVE" #edit in build-slackware-live.sh script too
 +DISTRONAME="Salix-xfce-14.2"
 +
 +if [ ! -z "$medialabel" ]; then
 +	LIVELABEL=$medialabel
 +fi
-+
+ 
  echo ""
  echo "*** Live system initialization ***"
- mount -v proc /proc -t proc
+@@ -6,7 +14,17 @@
  mount -v sysfs /sys -t sysfs
  
  /load_kernel_modules 2>/dev/null
@@ -951,7 +990,7 @@ diff -Naur slackware-live-0.4.orig/scripts/init slackware-live-0.4/scripts/init
  mdev -s
  
  mkdir /tmp #fuse needs /tmp
-@@ -25,42 +42,33 @@
+@@ -25,42 +43,33 @@
  	ifconfig eth0 $address netmask $netmask
  	route add default gw $gateway
  	mount -t nfs -o nolock $nfsroot /slroot/live/media
@@ -1012,7 +1051,7 @@ diff -Naur slackware-live-0.4.orig/scripts/init slackware-live-0.4/scripts/init
  	echo -n "Copying live system to RAM ..."
  	mkdir /slroot/live/tmp
  	mount --move /slroot/live/media /slroot/live/tmp
-@@ -70,14 +78,17 @@
+@@ -70,14 +79,17 @@
  	for bootfile in `find /slroot/live/tmp/boot -maxdepth 1 -type f`; do
  		cp $bootfile /slroot/live/media/boot/
  	done
@@ -1037,7 +1076,7 @@ diff -Naur slackware-live-0.4.orig/scripts/init slackware-live-0.4/scripts/init
  	mkdir /slroot/live/media/boot/optional
  	for modulename in `echo $include | sed 's/:/ /g'`; do #copy included optional modules
  		if [ -f /slroot/live/tmp/boot/optional/$modulename ]; then
-@@ -88,7 +99,7 @@
+@@ -88,7 +100,7 @@
  	umount /slroot/live/tmp
  	rmdir /slroot/live/tmp
  	mount -o remount,ro /slroot/live/media
@@ -1046,7 +1085,7 @@ diff -Naur slackware-live-0.4.orig/scripts/init slackware-live-0.4/scripts/init
  		eject $livedevice
  	fi
  	echo " done"
-@@ -96,15 +107,19 @@
+@@ -96,15 +108,19 @@
  
  #mount all modules in /live/modules/* except excluded ones
  mkdir /slroot/live/modules
@@ -1075,7 +1114,7 @@ diff -Naur slackware-live-0.4.orig/scripts/init slackware-live-0.4/scripts/init
  
  #load requested optional modules
  for modulename in `echo $include | sed 's/:/ /g'`; do
-@@ -113,63 +128,118 @@
+@@ -113,63 +129,118 @@
  		mount -o loop -t squashfs /slroot/live/media/boot/optional/$modulename /slroot/live/modules/$modulename
  		modulesbranches="/slroot/live/modules/$modulename=ro:$modulesbranches"
  		echo "Loading SquashFS module $modulename"
@@ -1228,7 +1267,7 @@ diff -Naur slackware-live-0.4.orig/scripts/init slackware-live-0.4/scripts/init
  
  #setup system tree
  for directory in /slroot/live/union/*; do #bind /live/union top directories into /
-@@ -184,62 +254,74 @@
+@@ -184,62 +255,74 @@
  mknod /slroot/dev/console c 5 1 2>/dev/null
  mknod /slroot/dev/null c 1 3 2>/dev/null #needed to mount /proc (rc.S) on read-only filesystem
  cat > /slroot/live/union/etc/fstab << END
@@ -1330,7 +1369,7 @@ diff -Naur slackware-live-0.4.orig/scripts/init slackware-live-0.4/scripts/init
  	sed	-e "s@\(/sbin/reboot\)@reboot -w; shutdown -k now \>/dev/null\n  cdrecord --eject dev=$livedevice \>/dev/null 2\>\&1\n  sleep 5\n  \1@" \
  		-e "s@\(/sbin/poweroff\)@poweroff -w; shutdown -k now \>/dev/null\n  cdrecord --eject dev=$livedevice \>/dev/null 2\>\&1\n  sleep 5\n  \1@" \
  		-i /slroot/live/union/etc/rc.d/rc.6
-@@ -247,6 +329,7 @@
+@@ -247,6 +330,7 @@
  
  #setup persistent homedir
  if [ ! -z "$home" ] && [ ! "$copy2ram" == "yes" ] && [ "$mediadetected" != "cd" ]; then
@@ -1338,7 +1377,7 @@ diff -Naur slackware-live-0.4.orig/scripts/init slackware-live-0.4/scripts/init
  	uid=1000
  	if [ -z "`grep "^[^:]\+:x:$uid:" /slroot/live/union/etc/passwd | cut -f1 -d:`" ]; then
  		uid=0
-@@ -254,44 +337,67 @@
+@@ -254,44 +338,67 @@
  	homedir=`grep "x:$uid:" /slroot/live/union/etc/passwd | cut -f6 -d:`
  	gid=`grep "x:$uid:" /slroot/live/union/etc/passwd | cut -f4 -d:`
  	if [ "$mediadetected" == "sd" ]; then
@@ -1437,7 +1476,7 @@ diff -Naur slackware-live-0.4.orig/scripts/init slackware-live-0.4/scripts/init
  		fi
  	else
  		echo "Setting up persistent home directory ($home)"
-@@ -299,22 +405,25 @@
+@@ -299,22 +406,25 @@
  	fi
  fi
  
@@ -1471,7 +1510,7 @@ diff -Naur slackware-live-0.4.orig/scripts/init slackware-live-0.4/scripts/init
  fi
  END
  		chmod +x /slroot/live/union/etc/profile.d/x.sh
-@@ -328,30 +437,67 @@
+@@ -328,30 +438,67 @@
  	then sed -i s/^export\ LANG=.*/export\ LANG=$locale/ /slroot/live/union/etc/profile.d/lang.sh
  	else echo "export LANG=$locale" >> /slroot/live/union/etc/profile.d/lang.sh
  	fi
@@ -1557,7 +1596,7 @@ diff -Naur slackware-live-0.4.orig/scripts/init slackware-live-0.4/scripts/init
  fi
  
  if [ ! -z "$tz" ]; then
-@@ -373,23 +519,36 @@
+@@ -373,23 +520,36 @@
  fi
  
  #detect fixed partitions
@@ -1605,7 +1644,7 @@ diff -Naur slackware-live-0.4.orig/scripts/init slackware-live-0.4/scripts/init
  done
  
  #setup root password
-@@ -404,10 +563,7 @@
+@@ -404,10 +564,7 @@
  umount /proc
  umount /sys
  mount -r -o remount /slroot 2>/dev/null #remount root directory read-only for normal startup
